#!/usr/bin/env bash

### START-OF-WIDGET-ICON-MAP
function __widget_icon_map() {
  case "$1" in
  "block-1")
    icon_result="▁"
    ;;
  "block-2")
    icon_result="▂"
    ;;
  "block-3")
    icon_result="▃"
    ;;
  "block-4")
    icon_result="▄"
    ;;
  "block-5")
    icon_result="▅"
    ;;
  "block-6")
    icon_result="▆"
    ;;
  "block-7")
    icon_result="▇"
    ;;
  "block-8")
    icon_result="█"
    ;;
  "battery_empty")
    icon_result="󰂎"
    ;;
  "battery_low")
    icon_result="󰁻"
    ;;
  "battery_medium")
    icon_result="󰁾"
    ;;
  "battery_full")
    icon_result="󰁹"
    ;;
  "clock")
    icon_result="󰥔"
    ;;
  "calendar")
    icon_result="󰃭"
    ;;
  "network_download")
    icon_result="󰇚"
    ;;
  "network_upload")
    icon_result="󰇟"
    ;;
  "disk")
    icon_result="󰋊"
    ;;
  "loading")
    icon_result="󰔟"
    ;;
  "volume_medium")
    icon_result="󰕾"
    ;;
  "volume_low")
    icon_result="󰕿"
    ;;
  "volume_high")
    icon_result="󰕼"
    ;;
  "volume_mute")
    icon_result="󰝟"
    ;;
  "cpu")
    icon_result="󰻠"
    ;;
  "coffee_on")
    icon_result="󰅶"
    ;;
  "coffee_off")
    icon_result="󰶞"
    ;;
  "memory")
    icon_result="󰍛"
    ;;
  "config")
    icon_result="󰒓"
    ;;
  "bluetooth")
    icon_result="󰂯"
    ;;
  "bluetooth_off")
    icon_result="󰂲"
    ;;
  "weather_clear_day")
    icon_result=""
    ;;
  "weather_clear_night")
    icon_result=""
    ;;
  "weather_partly_cloudy_day")
    icon_result=""
    ;;
  "weather_partly_cloudy_night")
    icon_result=""
    ;;
  "weather_cloudy_day")
    icon_result=""
    ;;
  "weather_cloudy_night")
    icon_result=""
    ;;
  "weather_fog_day")
    icon_result=""
    ;;
  "weather_fog_night")
    icon_result=""
    ;;
  "weather_rain_day")
    icon_result=""
    ;;
  "weather_rain_night")
    icon_result=""
    ;;
  "weather_snow_day")
    icon_result=""
    ;;
  "weather_snow_night")
    icon_result=""
    ;;
  "weather_hail_day")
    icon_result=""
    ;;
  "weather_hail_night")
    icon_result=""
    ;;
  "weather_sleet_day")
    icon_result=""
    ;;
  "weather_sleet_night")
    icon_result=""
    ;;
  "weather_thunderstorm_day")
    icon_result=""
    ;;
  "weather_thunderstorm_night")
    icon_result=""
    ;;
  "weather_default") icon_result="" ;;
  *)
    icon_result="󰐼"
    ;;
  esac
}
### END-OF-WIDGET-ICON-MAP
